functionsDirectory = "/Users/maxwellcochrane/AiBackend/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/maxwellcochrane/AiBackend/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/maxwellcochrane/AiBackend/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npx vite"
targetPort = 5173.0
port = 8888.0
autoLaunch = true

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@azure/ai-agents", "@azure/identity"]
  node_bundler = "esbuild"

[functions."chat"]
  timeout = 26